### ISSUE TITLE
triggertask +  task-launcher-yarn stream fails with  java.lang.NoSuchMethodError: javax.el.ExpressionFactory.newInstance()Ljavax/el/ExpressionFactory;

### ISSUE THREAD

**Issue by GlebMendrul** [spring-cloud-stream-app-starters/tasklauncher-yarn#3]
Hi, I'm running spring-cloud-dataflow-server-yarn-dist-1.2.0.RELEASE server in docker cloudera container with SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904-el6.parcel and hadoop-2.6.0-cdh5.11.1.

I have imported applications:
`app import --uri http://bit.ly/Bacon-RELEASE-stream-applications-kafka-10-maven`

and have the following stream: 
`stream create foo --definition "triggertask --uri=maven://org.springframework.cloud.task.app:timestamp-task:jar:1.0.0.BUILD-SNAPSHOT --fixed-delay=5 | task-launcher-yarn" --deploy`

When I deploy this stream to server, it fails with exception:

<pre>
2017-12-04 17:24:52,273 ERROR main o.s.b.SpringApplication:815 - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bindingService' defined in org.springframework.cloud.stream.config.BindingServiceConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.stream.binding.BindingService]: Factory method 'bindingService' threw exception; nested exception is javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.cloud.stream.app.task.launcher.yarn.sink.kafka.TaskLauncherYarnSinkKafka10Application.main(TaskLauncherYarnSinkKafka10Application.java:29) [classes!/:1.2.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [task-launcher-yarn-sink-kafka-10-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [task-launcher-yarn-sink-kafka-10-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [task-launcher-yarn-sink-kafka-10-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [task-launcher-yarn-sink-kafka-10-1.2.0.RELEASE.jar:1.2.0.RELEASE]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.stream.binding.BindingService]: Factory method 'bindingService' threw exception; nested exception is javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 26 common frames omitted
Caused by: javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:102) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:45) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolator(ConfigurationImpl.java:423) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(ConfigurationImpl.java:575) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getMessageInterpolator(ConfigurationImpl.java:364) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:144) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:331) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110) ~[validation-api-1.1.0.Final.jar!/:na]
	at org.springframework.validation.beanvalidation.CustomValidatorBean.afterPropertiesSet(CustomValidatorBean.java:71) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.<init>(BindingService.java:74) ~[spring-cloud-stream-1.2.1.RELEASE.jar!/:1.2.1.RELEASE]
	at org.springframework.cloud.stream.config.BindingServiceConfiguration.bindingService(BindingServiceConfiguration.java:102) ~[spring-cloud-stream-1.2.1.RELEASE.jar!/:1.2.1.RELEASE]
	at org.springframework.cloud.stream.config.BindingServiceConfiguration$$EnhancerBySpringCGLIB$$51fb52d5.CGLIB$bindingService$4(<generated>) ~[spring-cloud-stream-1.2.1.RELEASE.jar!/:1.2.1.RELEASE]
	at org.springframework.cloud.stream.config.BindingServiceConfiguration$$EnhancerBySpringCGLIB$$51fb52d5$$FastClassBySpringCGLIB$$aa72af57.invoke(<generated>) ~[spring-cloud-stream-1.2.1.RELEASE.jar!/:1.2.1.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cloud.stream.config.BindingServiceConfiguration$$EnhancerBySpringCGLIB$$51fb52d5.bindingService(<generated>) ~[spring-cloud-stream-1.2.1.RELEASE.jar!/:1.2.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 27 common frames omitted
Caused by: java.lang.NoSuchMethodError: javax.el.ExpressionFactory.newInstance()Ljavax/el/ExpressionFactory;
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:98) ~[hibernate-validator-5.3.4.Final.jar!/:5.3.4.Final]
	... 48 common frames omitted
</pre>

Could anyone please have a look and provide some assistance.

Thank you!

**Comment by GlebMendrul** [comment]
I can reproduce the same issue locally without  spring-cloud-dataflow-server-yarn.
Steps to reproduce: 

1. checkout repo
2. mvn clean install -PgenerateApps
3. cd apps/task-launcher-yarn-sink-kafka-10
4. mvn clean package
5. java -jar target/task-launcher-yarn-sink-kafka-10-2.0.0.BUILD-SNAPSHOT.jar

**Comment by jvalkeal** [comment]
You gotta love these deps pulled in by hadoop causing `java.lang.NoSuchMethodError: javax.el.ExpressionFactory.newInstance()Ljavax/el/ExpressionFactory`.

Excluding `javax.servlet.jsp:jsp-api` hopefully does a trick which we can try to do in pom structure but in a meanwhile you can also try to do this in your pom as well.

```
[INFO] org.springframework.cloud.stream.app:task-launcher-yarn-sink-kafka-10:jar:2.0.0.BUILD-SNAPSHOT
[INFO] +- org.springframework.cloud.stream.app:spring-cloud-starter-stream-sink-task-launcher-yarn:jar:2.0.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-deployer-yarn:jar:1.2.0.RELEASE:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-deployer-yarn-autoconfig:jar:1.2.0.RELEASE:compile
[INFO] |  |     +- org.springframework.cloud:spring-cloud-deployer-yarn:jar:1.2.0.RELEASE:compile
[INFO] |  |     |  +- org.springframework.data:spring-yarn-boot:jar:2.4.0.RELEASE:compile
[INFO] |  |     |  |  +- org.springframework.data:spring-yarn-core:jar:2.4.0.RELEASE:compile
[INFO] |  |     |  |  |  +- org.apache.hadoop:hadoop-common:jar:2.7.1:compile
[INFO] |  |     |  |  |  |  +- javax.servlet.jsp:jsp-api:jar:2.1:runtime


14:12 $ unzip -l jsp-api-2.1.jar |grep ExpressionFactory
     1079  2006-05-10 14:22   javax/el/ExpressionFactory.class

14:13 $ unzip -l tomcat-embed-el-8.5.23.jar |grep ExpressionFactory
     1053  2017-09-28 11:30   javax/el/ExpressionFactory$1.class
      797  2017-09-28 11:30   javax/el/ExpressionFactory$2.class
      797  2017-09-28 11:30   javax/el/ExpressionFactory$3.class
     1135  2017-09-28 11:30   javax/el/ExpressionFactory$CacheKey.class
     1630  2017-09-28 11:30   javax/el/ExpressionFactory$CacheValue.class
     9883  2017-09-28 11:30   javax/el/ExpressionFactory.class
     2813  2017-09-28 11:30   org/apache/el/ExpressionFactoryImpl.class

14:15 $ javap -classpath tomcat-embed-el-8.5.23.jar javax.el.ExpressionFactory
Compiled from "ExpressionFactory.java"
public abstract class javax.el.ExpressionFactory {
  public javax.el.ExpressionFactory();
  public static javax.el.ExpressionFactory newInstance();
  public static javax.el.ExpressionFactory newInstance(java.util.Properties);
  public abstract javax.el.ValueExpression createValueExpression(javax.el.ELContext, java.lang.String, java.lang.Class<?>);
  public abstract javax.el.ValueExpression createValueExpression(java.lang.Object, java.lang.Class<?>);
  public abstract javax.el.MethodExpression createMethodExpression(javax.el.ELContext, java.lang.String, java.lang.Class<?>, java.lang.Class<?>[]);
  public abstract java.lang.Object coerceToType(java.lang.Object, java.lang.Class<?>);
  public javax.el.ELResolver getStreamELResolver();
  public java.util.Map<java.lang.String, java.lang.reflect.Method> getInitFunctionMap();
  static java.lang.String access$000();
  static java.lang.String access$100();
  static {};
}

14:15 $ javap -classpath jsp-api-2.1.jar javax.el.ExpressionFactory
Compiled from "ExpressionFactory.java"
public abstract class javax.el.ExpressionFactory {
  public javax.el.ExpressionFactory();
  public abstract javax.el.ValueExpression createValueExpression(javax.el.ELContext, java.lang.String, java.lang.Class<?>);
  public abstract javax.el.ValueExpression createValueExpression(java.lang.Object, java.lang.Class<?>);
  public abstract javax.el.MethodExpression createMethodExpression(javax.el.ELContext, java.lang.String, java.lang.Class<?>, java.lang.Class<?>[]);
  public abstract java.lang.Object coerceToType(java.lang.Object, java.lang.Class<?>);
}
```
